
name: CI
on: [push, pull_request]

jobs:
  unit-tests:
    name: Unit tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
      - run: go test ./...
      - name: Upload coverage to codecov
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
